apiVersion: apps/v1
kind: Deployment
metadata:
  name: vid-browse-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vid-browse
  template:
    metadata:
      labels:
        app: vid-browse
    spec:
      containers:
        - name: vid-browse
          image: vid-browse:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: env-variables-k8
