apiVersion: apps/v1
kind: Deployment
metadata:
  name: vid-auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vid-auth
  template:
    metadata:
      labels:
        app: vid-auth
    spec:
      containers:
        - name: vid-auth
          image: vid-auth:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: env-variables-k8
