# microservices-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vid-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vid-gateway
  template:
    metadata:
      labels:
        app: vid-gateway
    spec:
      containers:
        - name: vid-gateway
          image: vid-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: env-variables-k8
            