apiVersion: v1
kind: Service
metadata:
  name: vid-browse-service
spec:
  selector:
    app: vid-browse
  ports:
    - protocol: TCP
      port: 3001  # Expose port 3001 for accessing vid-browse
      targetPort: 3001  # Use 3001 as the targetPort to match the containerPort of vid-browse
  type: LoadBalancer
