apiVersion: v1
kind: Service
metadata:
  name: vid-auth-service
spec:
  selector:
    app: vid-auth
  ports:
    - protocol: TCP
      port: 3008  # Expose port 3008 for accessing vid-auth
      targetPort: 3008  # Use 3008 as the targetPort to match the containerPort of vid-auth
  type: LoadBalancer
